name: GitHub Contribution Snake

on:
  schedule:
    # تحديث 4 مرات يومياً
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Generate GitHub Contribution Grid
        uses: Platane/snk@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: ahmedsabrari
          outputs: |
            snake/snake-dark.svg?color=dark
            snake/snake-dark-2.svg?color=dark&palette=github-dark
            snake/snake.svg?color=random
            snake/snake.gif?color=random-dark&palette=github-dark
          # خيارات إضافية
          period: "last_1_year"
          show_other_days: "true"
          
      - name: Deploy to Repository
        uses: JamesIves/github-pages-deploy-action@v4
        if: success()
        with:
          branch: main
          folder: snake
          clean: false
